services:
  app:
    build: .
    ports:
      - "26053:26053"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bookstore
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data: